name = "sharepoint2ics"
description = "Read a sharepoint calendar and write an appropriate ics file"
version = "0.5.0"

authors = ["Ansgar Esztermann"]
maintainers = ["Ansgar Esztermann <aeszter@mpinat.mpg.de>"]
maintainers-logins = ["aeszter"]
licenses = "MIT"

executables = ["sharepoint2ics"]
[[depends-on]]
florist = "*"
[[depends-on]]
florist_blady = "*"
[[depends-on]]
aws = "^21.0.0"
[[depends-on]]
adacgi = "*"
